macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.1.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.1.0/Contents/Home
    JET_PLATFORM: macos # used in release script
    JET_ARCH: aarch64
    JET_TEST_ENV: native
    GITHUB_TOKEN: ENCRYPTED[d6ff8cdc392157f211c754fa0763875434d1bfde0c00a05e48ba9470003a76c14c9213adb80623f81e13f2f0fa8fbd57]

  script: |
    ls script
    sudo script/install-clojure
    sudo script/install-leiningen
    script/install-graalvm
    export PATH=$GRAALVM_HOME/bin:$PATH
    java -version

    script/compile
    script/test

    VERSION=$(cat resources/JET_VERSION)
    arch=${JET_ARCH:-amd64}
    archive="jet-$VERSION-$JET_PLATFORM-$arch.tar.gz"
    tar zcvf "$archive" jet

    sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
    bb release-artifact "$archive" || true
  binaries_artifacts:
    path: "jet-*.tar.gz"
